### PR TITLE
add native.d.ts to package.json files & v.0.10.1

### PR DESCRIPTION
**Pull request by i-yusuf**

### CODE REVIEW

**Comment by jacobp100** [comment]
Thanks! I’ll try and get this published ASAP - when I’m back on my laptop

**Comment by i-yusuf** [comment]
It would be great. I developing our new product with this library. I'm waiting 😊

**Comment by i-yusuf** [comment]
Is there any progress?

**Comment by jacobp100** [comment]
@i-yusuf Sorry for the delay. Published now

**Comment by i-yusuf** [comment]
thanks!

**Pull request merged**
